#!/usr/bin/env python3
"""Render the three-path usage diagram (Read / AI / Collection) deterministically.

Unlike the PaperBanana workflow illustration, this figure needs no API key:
it is drawn with matplotlib from the labels below so it stays in sync with the
documented user flow and can be regenerated by anyone.

Usage:
  PYTHONUTF8=1 python pipeline/generate_usage_diagram.py            # both languages
  PYTHONUTF8=1 python pipeline/generate_usage_diagram.py --lang ko  # one language
"""
from __future__ import annotations

import argparse
from pathlib import Path

import matplotlib

matplotlib.use("Agg")
import matplotlib.pyplot as plt  # noqa: E402
from matplotlib import font_manager  # noqa: E402
from matplotlib.patches import FancyArrowPatch, FancyBboxPatch  # noqa: E402

ROOT = Path(__file__).resolve().parents[1]
OUTPUTS = {"ko": ROOT / "usage_workflow.png", "en": ROOT / "usage_workflow.en.png"}

LABELS = {
    "ko": {
        "title": "Paper Curation — 세 가지 사용 경로",
        "subtitle": "필요한 범위만 고른다 · 계획을 확인한 뒤 실행한다 · 자동 폴백 없음",
        "lanes": [
            ("Read", "읽기 · 내보내기", "API 키 불필요",
             ["웹 사이트 / 기존 리뷰 HTML", "카드 · 검색 · 타임라인 열람", "공개 기관표 · 보고서 내보내기"]),
            ("AI", "논문 AI", "선택한 제공자 하나",
             ["Zotero 항목 + 로컬 PDF", "리뷰 · 요약 · 질의 · 비교", "review.md · index.html · bibliography.json"]),
            ("Collection", "컬렉션 관리 · 선택 기능", "명시적으로 요청할 때만",
             ["Zotero 컬렉션 / 코퍼스 전체", "색인 · 지표 · 서지 DB · 오디오 · 타임라인", "동기화 · 배포 · 이메일은 확인 후 실행"]),
        ],
        "entry": ["Zotero 우클릭 메뉴\n(Paper Curio)", "명령줄\nrun_feature.py"],
        "engine_title": "공통 실행기 (paper-curation)",
        "engine_steps": ["레지스트리\nfeatures.json", "계획 (plan)\n요구조건 · 전송 대상 · 비용", "확인", "실행 (execute)"],
        "footer": [
            "자격증명: 환경변수 → OS 키 저장소 (credential:<provider>) · 평문 설정 없음",
            "안전장치: 코퍼스 예약·등록 잠금 · 비용 상한 · 실패 시 부분 결과 보존 · 다른 제공자로 자동 전송 없음",
        ],
        "columns": ["시작점", "작업", "산출물"],
    },
    "en": {
        "title": "Paper Curation — Three Usage Paths",
        "subtitle": "Choose only what you need · inspect the plan before executing · no silent fallback",
        "lanes": [
            ("Read", "Read / export", "no API key",
             ["Website / existing review HTML", "Browse cards, search, timelines", "Public institution table, report export"]),
            ("AI", "Paper AI", "one selected provider",
             ["Zotero item + local PDF", "Review, summary, chat, comparison", "review.md, index.html, bibliography.json"]),
            ("Collection", "Collection / optional", "only on explicit request",
             ["Zotero collection / whole corpus", "Index · metrics · bibliography · audio · timeline", "Sync, publish, email only after confirmation"]),
        ],
        "entry": ["Zotero context menu\n(Paper Curio)", "Command line\nrun_feature.py"],
        "engine_title": "Shared runner (paper-curation)",
        "engine_steps": ["Registry\nfeatures.json", "Plan\nrequirements, destination, cost", "Confirm", "Execute"],
        "footer": [
            "Credentials: environment → OS keyring (credential:<provider>); no plaintext settings",
            "Safeguards: corpus reservation/index locks · cost ceiling · partial results kept on failure · no cross-provider fallback",
        ],
        "columns": ["Start", "Work", "Output"],
    },
}

LANE_COLORS = {"Read": "#DCEFE3", "AI": "#DDE7F7", "Collection": "#F6E7D8"}
LANE_EDGES = {"Read": "#3F8F5F", "AI": "#3B6BB5", "Collection": "#C57A2E"}


def _font() -> str:
    preferred = ["Apple SD Gothic Neo", "AppleGothic", "NanumGothic", "Noto Sans CJK KR", "DejaVu Sans"]
    available = {font.name for font in font_manager.fontManager.ttflist}
    return next(name for name in preferred if name in available)


def _box(ax, x, y, w, h, text, *, face, edge, size=11, weight="normal", radius=0.12):
    ax.add_patch(FancyBboxPatch((x, y), w, h, boxstyle=f"round,pad=0.02,rounding_size={radius}",
                                facecolor=face, edgecolor=edge, linewidth=1.6))
    ax.text(x + w / 2, y + h / 2, text, ha="center", va="center", fontsize=size, weight=weight, wrap=True)


def _arrow(ax, start, end, color="#555555"):
    ax.add_patch(FancyArrowPatch(start, end, arrowstyle="-|>", mutation_scale=16, linewidth=1.4, color=color))


def render(lang: str) -> Path:
    labels = LABELS[lang]
    plt.rcParams["font.family"] = _font()
    plt.rcParams["axes.unicode_minus"] = False
    fig, ax = plt.subplots(figsize=(16, 9), dpi=150)
    ax.set_xlim(0, 16)
    ax.set_ylim(0, 9)
    ax.axis("off")

    ax.text(8, 8.55, labels["title"], ha="center", va="center", fontsize=22, weight="bold")
    ax.text(8, 8.1, labels["subtitle"], ha="center", va="center", fontsize=12, color="#444444")

    # Entry points (left) feeding the shared runner.
    for index, text in enumerate(labels["entry"]):
        y = 6.55 - index * 1.15
        _box(ax, 0.35, y, 2.2, 0.85, text, face="#F2F2F2", edge="#777777", size=11)
        _arrow(ax, (2.55, y + 0.42), (3.05, 6.35))

    # Shared runner pipeline.
    _box(ax, 3.05, 5.55, 12.6, 1.6, "", face="#FAFAFA", edge="#999999", radius=0.2)
    ax.text(9.35, 6.95, labels["engine_title"], ha="center", va="center", fontsize=12.5, weight="bold", color="#333333")
    step_width, gap, x = 2.6, 0.5, 3.4
    for index, step in enumerate(labels["engine_steps"]):
        face = "#FFF4CC" if index == 2 else "#FFFFFF"
        _box(ax, x, 5.75, step_width, 0.95, step, face=face, edge="#888888", size=10.5)
        if index < len(labels["engine_steps"]) - 1:
            _arrow(ax, (x + step_width, 6.22), (x + step_width + gap, 6.22))
        x += step_width + gap

    # Column headings for lanes.
    column_x = [5.2, 9.4, 13.6]
    for cx, heading in zip(column_x, labels["columns"]):
        ax.text(cx, 5.2, heading, ha="center", va="center", fontsize=11, color="#666666", weight="bold")

    # Three lanes.
    lane_height, lane_gap, top = 1.15, 0.22, 5.0
    for index, (key, name, requirement, cells) in enumerate(labels["lanes"]):
        y = top - lane_height - index * (lane_height + lane_gap)
        _box(ax, 0.35, y, 15.3, lane_height, "", face=LANE_COLORS[key], edge=LANE_EDGES[key], radius=0.18)
        ax.text(0.55, y + lane_height - 0.32, key, ha="left", va="center", fontsize=13, weight="bold", color=LANE_EDGES[key])
        ax.text(0.55, y + lane_height / 2, name, ha="left", va="center", fontsize=10.5, color="#333333")
        ax.text(0.55, y + 0.26, requirement, ha="left", va="center", fontsize=9.5, color="#555555")
        cell_width = 3.4
        for cx, text in zip(column_x, cells):
            _box(ax, cx - cell_width / 2, y + 0.2, cell_width, lane_height - 0.4, text, face="#FFFFFF", edge=LANE_EDGES[key], size=9.5)
        for left, right in zip(column_x, column_x[1:]):
            _arrow(ax, (left + cell_width / 2, y + lane_height / 2), (right - cell_width / 2, y + lane_height / 2), color=LANE_EDGES[key])

    for index, line in enumerate(labels["footer"]):
        ax.text(8, 0.62 - index * 0.32, line, ha="center", va="center", fontsize=10.5, color="#333333")

    output = OUTPUTS[lang]
    fig.savefig(output, bbox_inches="tight", facecolor="white")
    plt.close(fig)
    return output


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--lang", choices=sorted(OUTPUTS), action="append")
    args = parser.parse_args(argv)
    for lang in args.lang or sorted(OUTPUTS):
        print(render(lang))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
