"""
배포 준비: PNG→WebP 변환 + text.md gitignore + HTML 경로 업데이트.

Cloudflare Workers(Static Assets)가 master 브랜치의 docs/ 를 자동으로
배포한다. 따라서 이 스크립트는 docs/ 만 master에 commit/push 한다.
(구 gh-pages subtree 방식은 제거됨)

Usage:
  PYTHONUTF8=1 python prepare_deploy.py --topic ai4s
  PYTHONUTF8=1 python prepare_deploy.py --topic ai4s --quality 90    # WebP 품질 (기본 90)
  PYTHONUTF8=1 python prepare_deploy.py --topic ai4s --dry-run       # 변환 없이 크기 예상만
  PYTHONUTF8=1 python prepare_deploy.py --topic ai4s --push          # 변환 후 master push (Cloudflare 자동 배포)

단계:
  1. .gitignore에 text.md 추가
  2. papers/*/figures/*.png → *.webp 변환 (quality 90, lossless 아님)
  3. papers/*/index.html, papers/*/review.md에서 .png → .webp 경로 업데이트
  4. {topic}/index.html에서 .png → .webp 경로 업데이트 (figure 참조만, 타임라인은 PNG 유지)
  5. 원본 PNG 삭제
  6. (선택) git add docs/ + commit + push origin master  → Cloudflare 자동 배포
"""

import argparse
import os
import re
import subprocess
import sys
from concurrent.futures import ThreadPoolExecutor
from pathlib import Path

from config_loader import get_github_branch, PAPERS_DIR as _PAPERS_DIR, DOCS_DIR, PROJECT_ROOT, get_topic_dir
PAPERS_DIR = str(_PAPERS_DIR)
REPO = str(PROJECT_ROOT)


def ensure_gitignore():
    """text.md를 .gitignore에 추가."""
    gi_path = os.path.join(REPO, ".gitignore")
    existing = ""
    if os.path.exists(gi_path):
        with open(gi_path, "r", encoding="utf-8") as f:
            existing = f.read()

    additions = []
    for pattern in ["papers/*/text.md", "__pycache__/", "_update_force_checkpoint.json",
                     "_regen_*.py", "_update_force.log"]:
        if pattern not in existing:
            additions.append(pattern)

    if additions:
        with open(gi_path, "a", encoding="utf-8") as f:
            f.write("\n# Auto-generated by prepare_deploy.py\n")
            for p in additions:
                f.write(f"{p}\n")
        print(f"  .gitignore: added {len(additions)} patterns")
    else:
        print("  .gitignore: already up to date")


MIN_VALID_WEBP_BYTES = 200  # anything smaller is almost certainly corrupt


def convert_png_to_webp(png_path, quality=90):
    """PNG → WebP 변환. 성공 시 (원본크기, 변환크기, webp_path) 반환.

    실패하거나 손상된 WebP (너무 작음)의 경우 dangling webp 파일을
    정리하고 None 을 반환해, 뒤따르는 Step 5 의 PNG 삭제 로직이
    원본을 실수로 지우지 않도록 한다."""
    webp_path = png_path.replace(".png", ".webp")
    try:
        from PIL import Image
        img = Image.open(png_path)
        img.save(webp_path, "WEBP", quality=quality)
        orig_size = os.path.getsize(png_path)
        webp_size = os.path.getsize(webp_path)
        if webp_size < MIN_VALID_WEBP_BYTES:
            raise RuntimeError(
                f"WebP output too small ({webp_size} bytes, likely corrupt)")
        return orig_size, webp_size, webp_path
    except Exception as e:
        print(f"  ERR: {png_path}: {e}")
        # Clean up any partial/corrupt webp file so Step 5 does not
        # treat it as a successful conversion and delete the PNG.
        if os.path.exists(webp_path):
            try:
                os.remove(webp_path)
            except Exception as cleanup_err:
                print(f"    (failed to clean dangling webp: {cleanup_err})")
        return 0, 0, None


def update_html_refs(file_path, fig_only=False):
    """HTML/MD 파일에서 figure .png → .webp 참조 업데이트."""
    with open(file_path, "r", encoding="utf-8") as f:
        content = f.read()

    if fig_only:
        # 타임라인 PNG는 유지, figure 참조만 변환
        new_content = re.sub(r'(figures/[^"\']+)\.png', r'\1.webp', content)
    else:
        # 모든 .png → .webp (review.md, papers/*/index.html)
        new_content = re.sub(r'(figures/[^)\s"\']+)\.png', r'\1.webp', content)

    if new_content != content:
        with open(file_path, "w", encoding="utf-8") as f:
            f.write(new_content)
        return True
    return False


def main():
    parser = argparse.ArgumentParser(description="Prepare for GitHub Pages deployment")
    parser.add_argument("--topic", default="ai4s")
    parser.add_argument("--quality", type=int, default=90, help="WebP quality (1-100)")
    parser.add_argument("--dry-run", action="store_true", help="Estimate only, no conversion")
    parser.add_argument("--push", action="store_true", help="Git add + commit + push after conversion")
    parser.add_argument("--workers", type=int, default=8, help="Parallel workers for conversion")
    args = parser.parse_args()

    topic_dir = str(get_topic_dir(args.topic))

    # Step 1: .gitignore
    print("Step 1: .gitignore")
    if not args.dry_run:
        ensure_gitignore()

    # Step 2: Find all figure PNGs
    print("\nStep 2: Finding PNGs...")
    png_files = []
    for slug in os.listdir(PAPERS_DIR):
        fig_dir = os.path.join(PAPERS_DIR, slug, "figures")
        if not os.path.isdir(fig_dir):
            continue
        for f in os.listdir(fig_dir):
            if f.endswith(".png"):
                png_files.append(os.path.join(fig_dir, f))

    total_png_size = sum(os.path.getsize(f) for f in png_files)
    print(f"  Found {len(png_files)} PNGs ({total_png_size / 1048576:.0f} MB)")

    if args.dry_run:
        # Estimate: sample 10 files
        sample = png_files[:10]
        sample_orig = sum(os.path.getsize(f) for f in sample)
        sample_webp = 0
        for f in sample:
            orig, webp, _ = convert_png_to_webp(f, args.quality)
            sample_webp += webp
            # Clean up test webp
            wp = f.replace(".png", ".webp")
            if os.path.exists(wp):
                os.remove(wp)
        if sample_orig > 0:
            ratio = sample_webp / sample_orig
            est_total = total_png_size * ratio / 1048576
            print(f"\n  Estimated WebP size: {est_total:.0f} MB ({ratio:.0%} of original)")
            print(f"  Savings: {(total_png_size / 1048576) - est_total:.0f} MB")
        return

    # Step 3: Convert PNGs to WebP (parallel)
    print(f"\nStep 3: Converting to WebP (quality={args.quality})...")
    total_orig = 0
    total_webp = 0
    converted = 0

    with ThreadPoolExecutor(max_workers=args.workers) as executor:
        futures = {executor.submit(convert_png_to_webp, f, args.quality): f for f in png_files}
        for future in futures:
            orig, webp, webp_path = future.result()
            if webp_path:
                total_orig += orig
                total_webp += webp
                converted += 1

    print(f"  Converted: {converted}/{len(png_files)}")
    print(f"  {total_orig / 1048576:.0f} MB → {total_webp / 1048576:.0f} MB "
          f"({total_webp / max(1, total_orig):.0%})")

    # Step 4: Update HTML/MD references (.png → .webp where .webp exists)
    # Always run regardless of PNG conversion count — HTML may have been
    # regenerated with .png refs after a previous PNG→WebP conversion.
    print("\nStep 4: Updating references...")
    updated = 0
    for slug in os.listdir(PAPERS_DIR):
        slug_dir = os.path.join(PAPERS_DIR, slug)
        if not os.path.isdir(slug_dir):
            continue
        # Only update if .webp figures actually exist
        fig_dir = os.path.join(slug_dir, "figures")
        has_webp = os.path.isdir(fig_dir) and any(f.endswith(".webp") for f in os.listdir(fig_dir))
        if not has_webp:
            continue
        for fname in ["index.html", "review.md"]:
            fpath = os.path.join(slug_dir, fname)
            if os.path.exists(fpath) and update_html_refs(fpath):
                updated += 1

    # Update topic index.html (figures only, keep timeline PNGs)
    topic_index = os.path.join(topic_dir, "index.html")
    if os.path.exists(topic_index) and update_html_refs(topic_index, fig_only=True):
        updated += 1

    print(f"  Updated: {updated} files")

    # Step 5: Delete original PNGs (only when WebP is verifiably good).
    # Double-defense against WebP-conversion races: we require the WebP
    # to actually exist AND to be at least MIN_VALID_WEBP_BYTES, which
    # catches cases where Pillow crashed halfway and left a tiny or
    # corrupt output. Any PNG preserved by this guard is logged so the
    # operator can investigate and retry.
    print("\nStep 5: Deleting original PNGs...")
    deleted = 0
    preserved = 0
    for png_path in png_files:
        webp_path = png_path.replace(".png", ".webp")
        if not os.path.exists(webp_path):
            preserved += 1
            print(f"  KEEP: {png_path} (no WebP)")
            continue
        webp_size = os.path.getsize(webp_path)
        if webp_size < MIN_VALID_WEBP_BYTES:
            preserved += 1
            print(f"  KEEP: {png_path} (WebP too small: {webp_size} bytes)")
            continue
        os.remove(png_path)
        deleted += 1
    print(f"  Deleted: {deleted} PNGs, Preserved: {preserved}")

    # Step 6: Commit docs/ changes and push to master (Cloudflare auto-deploys)
    if args.push:
        print("\nStep 6: Git commit + push to master (Cloudflare will auto-deploy)...")
        os.chdir(REPO)

        subprocess.run(["git", "add", "docs/"], check=True)
        result = subprocess.run(
            ["git", "diff", "--cached", "--quiet"],
            capture_output=True
        )
        if result.returncode != 0:  # there are staged changes
            subprocess.run(["git", "commit", "-m",
                            f"Deploy: PNG→WebP conversion, {converted} figures, "
                            f"{total_orig // 1048576}→{total_webp // 1048576}MB\n\n"
                            f"Co-Authored-By: Claude Opus 4.6 (1M context) <noreply@anthropic.com>"],
                           check=True)
            subprocess.run(["git", "push", "origin", "master"], check=True)
            print("  Pushed to master — Cloudflare Workers will auto-deploy")
        else:
            print("  No staged changes to commit")
    else:
        print("\n(--push 없이 실행됨. git push는 수동으로)")

    print(f"\nDone! Total savings: {(total_orig - total_webp) / 1048576:.0f} MB")


if __name__ == "__main__":
    main()
